#Configuration
#Tue May 26 22:46:20 GMT-07:00 2026
pdf.export.lastFolder=C\:\\Users\\Dios Gorila\\Downloads
registration.window.height=711
registration.window.width=985
registration.window.x=532
registration.window.y=492
ui.theme=light
