#Configuration
#Mon Jun 08 03:44:09 GMT-07:00 2026
pdf.export.lastFolder=C\:\\Users\\Dios Gorila\\Downloads
registration.window.height=600
registration.window.width=961
registration.window.x=443
registration.window.y=274
ui.theme=light
