#Configuration
#Sun May 10 23:00:24 GMT-07:00 2026
pdf.export.lastFolder=C\:\\Users\\Dios Gorila\\Downloads
registration.window.height=500
registration.window.width=935
registration.window.x=460
registration.window.y=315
ui.theme=light
