# Añadimos parametros de seguridad en el db.url

db.url=jdbc:mysql://127.0.0.1:3306/cinerea_game?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=Determination
db.driver=com.mysql.cj.jdbc.Driver