# Añadimos parametros de seguridad en el db.url

db.url=jdbc:mysql://127.0.0.1:3306/cinerea_game?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=false
db.user=root
db.password=Grantormenta011206.
db.driver=com.mysql.cj.jdbc.Driver